-- 141_revoke_client_truncate.sql
--
-- CRITICAL: the anon key can TRUNCATE most of the database.
--
-- ================= WHAT WAS FOUND =================
-- Every table in `public` carries TRUNCATE for both `anon` and `authenticated`,
-- inherited from this project's ALTER DEFAULT PRIVILEGES (see house rule 5b,
-- added after migs 139/140 found the same hole on two tables). TRUNCATE
-- **ignores row-level security entirely**, so RLS -- the control this whole
-- schema relies on -- provides no protection against it.
--
-- Verified against PRODUCTION on 2026-07-27 as the `anon` role, in a
-- transaction that was rolled back. Every one of these succeeded and emptied
-- the table:
--
--   platform_settings      60 rows -> 0   (COD caps, fee rules, ops webhook,
--                                          functions_base_url — wiping this
--                                          silently disables dispatch alerting
--                                          and every push)
--   order_status_events    90 rows -> 0   (the order audit trail)
--   push_tokens            40 rows -> 0
--   loyalty_points_ledger  30 rows -> 0
--   order_financials        9 rows -> 0   (ALL commission records — the
--                                          billing basis for every merchant)
--   driver_earnings         9 rows -> 0
--   credit_ledger           8 rows -> 0   (customer wallet balances)
--   kyc_documents           0 rows -> 0   (empty today; identity documents
--                                          the moment onboarding starts)
--
-- The anon key is PUBLIC by design: it ships inside every app binary and is
-- readable by anyone who downloads the app. So this is not a theoretical
-- privilege-escalation chain -- it is a single statement from an unauthenticated
-- stranger.
--
-- Some tables (orders, users, addresses) happened to resist because Postgres
-- refuses to truncate a table referenced by a foreign key. That is incidental
-- protection from the FK graph, NOT a security control: `truncate ... cascade`
-- is the documented way around it, and any table at the edge of the graph has
-- no such luck. Nothing here should depend on it.
--
-- ================= THE FIX =================
-- Revoke TRUNCATE (and TRIGGER and REFERENCES, which no client role has any
-- business holding) from anon and authenticated on every table in `public`,
-- and change the default privileges so new tables never inherit them again.
--
-- SELECT/INSERT/UPDATE/DELETE are deliberately left exactly as they are: those
-- are the privileges RLS actually governs, and changing them here would break
-- the apps. This migration removes only what RLS cannot defend.

do $$
declare r record; n int := 0;
begin
  for r in
    select c.oid::regclass::text as tbl
      from pg_class c join pg_namespace n2 on n2.oid = c.relnamespace
     where n2.nspname = 'public' and c.relkind in ('r','p')
  loop
    -- TRUNCATE bypasses RLS. TRIGGER lets a client attach code to a table.
    -- REFERENCES lets a client create FKs against it (a lock/DoS surface).
    execute format('revoke truncate, trigger, references on %s from anon, authenticated', r.tbl);
    n := n + 1;
  end loop;
  raise notice 'revoked truncate/trigger/references on % public tables', n;
end $$;

-- Reduce the source too. NOTE this only half-works, and the limitation matters:
-- pg_default_acl carries entries from TWO grantors, `postgres` and
-- `supabase_admin`. This statement runs as `postgres`, which on Supabase is NOT
-- a superuser and is not a member of `supabase_admin` (verified 2026-07-27), so
-- the supabase_admin default entry cannot be altered from a migration at all --
-- the same ownership limit already documented for `spatial_ref_sys` (mig 102).
--
-- Consequence: a table created by supabase_admin (i.e. through the Dashboard or
-- platform tooling) can still inherit TRUNCATE. Tables created by migrations
-- run as postgres will not. **House rule 5b stands regardless: every new table
-- gets an explicit `revoke all ... from public, anon, authenticated` before its
-- real grants.** Do not rely on the default alone.
alter default privileges in schema public
  revoke truncate, trigger, references on tables from anon, authenticated;

-- spatial_ref_sys is owned by supabase_admin (PostGIS), so `postgres` cannot
-- revoke on it; it is reference data regenerated by CREATE EXTENSION, and its
-- exposure is already a documented accepted finding. Attempt it anyway and
-- ignore the failure rather than letting one un-ownable table abort the sweep.
do $$
begin
  execute 'revoke truncate on public.spatial_ref_sys from anon, authenticated';
exception when insufficient_privilege or others then
  raise notice 'spatial_ref_sys: not owned by this role, left as-is (accepted finding)';
end $$;

comment on schema public is
  'Application schema. NOTE: ALTER DEFAULT PRIVILEGES here grants broad rights to anon/authenticated on new objects; mig 141 revoked TRUNCATE/TRIGGER/REFERENCES from existing tables AND from the defaults. TRUNCATE ignores RLS, so it must never be held by a client role — see house rule 5b in CLAUDE.md.';
